#!/usr/bin/env python3
"""Build, bundle and push badge apps without the web IDE.

  python app/tools/badge.py build  <target>   # app/dist/<slug>/ + app/dist/<slug>.lua
  python app/tools/badge.py push   <target>   # build, then upload over USB serial
  python app/tools/badge.py img    <in.png> <out.bin> [--size WxH]
  python app/tools/badge.py ports              # list serial ports

Targets are in TARGETS below. `app/dist/<slug>.lua` is a single file for the
IDE's **Import app** (code only, no images). `push` uploads the whole folder,
images included, using the same console protocol as the IDE (`put`, `reload`).

Needs: pyserial for push, Pillow for images (pip install -r app/tools/requirements.txt).
"""

import argparse
import glob
import re
import sys
import time
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
DIST = APP / "dist"

COMMON = {"api": "2", "heap_kb": "48", "wake_lock": "1"}
DRIVERS = ("game", "preview")   # interchangeable modules behind require("driver")

TARGETS = {
    "goose": {"dir": "goose", "driver": "game",
              "manifest": {"slug": "goose_doctor", "name": "Goose Doctor", "icon": "GD"}},
    "preview": {"dir": "goose", "driver": "preview",
                "manifest": {"slug": "goose_preview", "name": "Goose UI Preview", "icon": "GP"}},
    "diag": {"dir": "diag"},    # single file with its own manifest header
}

OPEN, CLOSE = "--[==[badge-app", "]==]"
MAIN_LIMIT = 64 * 1024          # IDE limit for main.lua
APP_QUOTA = 64 * 1024           # per-app storage quota (BADGE_API.md, badge.fs)
SHARE_LIMIT = 48 * 1024         # Share app bundle cap


# --- build ------------------------------------------------------------------

def split_header(src):
    """Return (manifest dict, code) for a single-file app with a header."""
    lines = src.splitlines(keepends=True)
    if not lines or lines[0].strip() != OPEN:
        return None, src
    end = next(i for i, l in enumerate(lines) if l.strip() == CLOSE)
    manifest = {}
    for l in lines[1:end]:
        l = l.strip()
        if l and not l.startswith("#"):
            k, v = l.split("=", 1)
            manifest[k.strip()] = v.strip()
    return manifest, "".join(lines[end + 1:]).lstrip("\n")


def manifest_text(m):
    return "".join(f"{k}={v}\n" for k, v in m.items())


def collect(target):
    """Return (manifest, {module name: source}, {bin name: bytes})."""
    t = TARGETS[target]
    src_dir = APP / t["dir"]
    main_src = (src_dir / "main.lua").read_text()
    header, main_code = split_header(main_src)

    if "driver" not in t:       # plain single-file app
        return header, {"main": main_code}, {}

    modules = {"main": main_src}
    for f in sorted(src_dir.glob("*.lua")):
        name = f.stem
        if name == "main" or (name in DRIVERS and name != t["driver"]):
            continue
        modules[name] = f.read_text()
    modules["driver"] = f'return require("{t["driver"]}")\n'

    images = {}
    for png in sorted((src_dir / "img").glob("*.png")):
        images[png.stem + ".bin"] = png_to_bin(png)
    for b in sorted((src_dir / "img").glob("*.bin")):
        images[b.name] = b.read_bytes()
    return {**t["manifest"], **COMMON}, modules, images


def bundle(manifest, modules):
    """Inline every module into one importable file; returns (text, line map)."""
    out = [OPEN + "\n", manifest_text(manifest), CLOSE + "\n",
           "-- GENERATED by app/tools/badge.py from app/ sources. Do not edit.\n"]
    if len(modules) > 1:
        out.append(
            "local __mods, __cache = {}, {}\n"
            "local function require(name)\n"
            "  local v = __cache[name]\n"
            "  if v ~= nil then return v end\n"
            "  local f = __mods[name]\n"
            "  if not f then error(\"module not found: \" .. name, 2) end\n"
            "  v = f()\n"
            "  if v == nil then v = true end\n"
            "  __cache[name] = v\n"
            "  return v\n"
            "end\n")
    line_map = []
    for name, src in modules.items():
        if name == "main":
            continue
        out.append(f"__mods[{name!r}] = function()  -- ==== {name}.lua ====\n")
        line_map.append((sum(s.count("\n") for s in out) + 1, name))
        out.append(src if src.endswith("\n") else src + "\n")
        out.append("end\n")
    main_code = split_header(modules["main"])[1]
    out.append("-- ==== main.lua ====\n")
    line_map.append((sum(s.count("\n") for s in out) + 1, "main"))
    out.append(main_code)
    return "".join(out), line_map


def build(target):
    manifest, modules, images = collect(target)
    slug = manifest["slug"]
    out_dir = DIST / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.iterdir():
        old.unlink()

    files = {"manifest.cfg": manifest_text(manifest).encode()}
    for name, src in modules.items():
        code = split_header(src)[1] if name == "main" else src
        files[f"{name}.lua"] = code.encode()
    files.update(images)
    for name, data in files.items():
        (out_dir / name).write_bytes(data)

    single, line_map = bundle(manifest, modules)
    single_path = DIST / f"{slug}.lua"
    single_path.write_text(single)

    total = sum(len(d) for d in files.values())
    print(f"built {slug}: {len(files)} files, {total} B -> {out_dir.relative_to(APP.parent)}/")
    print(f"  single file for Import app: {single_path.relative_to(APP.parent)} "
          f"({len(single.encode())} B)")
    print("  error line numbers in the single file:",
          ", ".join(f"{n}.lua from line {l}" for l, n in line_map))
    if images:
        print(f"  note: {len(images)} image(s) are only uploaded by `push`, not by Import app")
    if len(single.encode()) > MAIN_LIMIT:
        print(f"  WARNING: single file is over the IDE's {MAIN_LIMIT} B main.lua limit")
    if total > APP_QUOTA:
        print(f"  WARNING: {total} B is over the {APP_QUOTA} B per-app storage quota")
    elif total > SHARE_LIMIT:
        print(f"  note: over {SHARE_LIMIT} B, so the Share app can't send it to other badges")
    return slug, files


# --- images -----------------------------------------------------------------

def png_to_bin(path, size=None):
    """PNG -> LVGL v9 RGB565A8 .bin, same format as the IDE's icon.bin."""
    from PIL import Image
    im = Image.open(path).convert("RGBA")
    if size:
        im = im.resize(size, Image.LANCZOS)
    w, h = im.size
    px = im.tobytes()
    out = bytearray(12 + w * h * 3)
    out[0:4] = bytes([0x19, 0x14, 0, 0])           # magic, RGB565A8, flags
    out[4:12] = (w.to_bytes(2, "little") + h.to_bytes(2, "little")
                 + (w * 2).to_bytes(2, "little") + b"\0\0")
    alpha = 12 + w * h * 2
    for i in range(w * h):
        r, g, b, a = px[i * 4:i * 4 + 4]
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out[12 + i * 2] = c & 0xFF
        out[13 + i * 2] = c >> 8
        out[alpha + i] = a
    return bytes(out)


# --- push -------------------------------------------------------------------

CHUNK, PAUSE = 128, 0.02     # badge RX ring is 256 B: pace writes like the IDE


def find_port():
    ports = sorted(glob.glob("/dev/cu.usbmodem*") + glob.glob("/dev/ttyACM*"))
    if not ports:
        sys.exit("No badge found. Plug it in (badge off, plug USB, badge on, "
                 "don't hold Start) and close the IDE tab, which holds the port.")
    return ports[0]


class Console:
    def __init__(self, port):
        import serial
        self.s = serial.Serial(port, 115200, timeout=0.05)
        self.buf = ""

    def line(self, text):
        self.s.write((text + "\r").encode())

    def raw(self, data):
        for i in range(0, len(data), CHUNK):
            self.s.write(data[i:i + CHUNK])
            time.sleep(PAUSE)

    def wait(self, pattern, timeout=5.0):
        end = time.time() + timeout
        while time.time() < end:
            self.buf += self.s.read(512).decode(errors="replace")
            i = self.buf.find(pattern)
            if i >= 0:
                got, self.buf = self.buf[:i + len(pattern)], self.buf[i + len(pattern):]
                return got
        raise TimeoutError(f'no "{pattern}" from the badge after {timeout:.0f} s '
                           f"(last output: {self.buf[-200:]!r})")


def push(target, port):
    slug, files = build(target)
    port = port or find_port()
    print(f"pushing to {port} ...")
    c = Console(port)
    c.line("")
    c.wait("badge> ", 3)
    if any(n.endswith(".bin") for n in files):
        c.buf = ""
        c.line("put --binary")
        if "PUT BINARY OK" not in c.wait("badge> ", 5):
            sys.exit("This badge's firmware can't receive images; update its firmware.")
    remote = f"/littlefs/apps/{slug}"
    c.line(f"mkdir {remote}")
    c.wait("badge> ")
    for name in sorted(files):
        data = files[name]
        print(f"  {name} ({len(data)} B) ...", end=" ", flush=True)
        c.buf = ""
        c.line(f"put {remote}/{name} {len(data)}")
        c.wait("READY")
        c.raw(data)
        c.wait(f"OK {len(data)}", 20)
        print("ok")
    c.buf = ""
    c.line("reload")
    try:
        c.wait("reload:", 8)
        print(f"done: open '{files['manifest.cfg'].decode().split('name=')[1].splitlines()[0]}'"
              " from the badge launcher")
    except TimeoutError:
        print("uploaded, but reload wasn't confirmed: reboot the badge if the app doesn't appear")


# --- cli --------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    for cmd in ("build", "push"):
        sp = sub.add_parser(cmd)
        sp.add_argument("target", choices=TARGETS)
        if cmd == "push":
            sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp = sub.add_parser("img")
    sp.add_argument("png")
    sp.add_argument("out")
    sp.add_argument("--size", help="resize to WxH first, e.g. 56x56")
    sub.add_parser("ports")
    a = p.parse_args()

    if a.cmd == "build":
        build(a.target)
    elif a.cmd == "push":
        push(a.target, a.port)
    elif a.cmd == "img":
        size = tuple(int(n) for n in re.split("[x×]", a.size)) if a.size else None
        data = png_to_bin(a.png, size)
        Path(a.out).write_bytes(data)
        print(f"wrote {a.out}: {len(data)} B")
    elif a.cmd == "ports":
        print("\n".join(glob.glob("/dev/cu.usbmodem*") + glob.glob("/dev/ttyACM*")) or "none")


if __name__ == "__main__":
    main()
