#!/usr/bin/env python3
"""Build, bundle and push badge apps without the web IDE.

  python app/tools/badge.py build  <target>   # app/dist/<slug>/ + app/dist/<slug>.lua
  python app/tools/badge.py push   <target>   # build, then upload over USB serial
  python app/tools/badge.py img    <in.png> <out.bin> [--size WxH]
  python app/tools/badge.py ports              # list serial ports
  python app/tools/badge.py logs               # print the badge's USB serial console

Targets are in TARGETS below. `app/dist/<slug>.lua` is a single file for the
IDE's **Import app** (code only, no images). `push` uploads the whole folder,
images included, using the same console protocol as the IDE (`put`, `reload`).

Needs: pyserial for push, Pillow for images (pip install -r app/tools/requirements.txt).
"""

import argparse
import glob
import re
import sys
import time
from pathlib import Path

APP = Path(__file__).resolve().parent.parent
DIST = APP / "dist"

COMMON = {"api": "2", "heap_kb": "48", "wake_lock": "1"}
DRIVERS = ("game", "preview")   # interchangeable modules behind require("driver")

TARGETS = {
    "goose": {"dir": "goose", "driver": "game",
              "manifest": {"slug": "goose_doctor", "name": "Goose Doctor", "icon": "GD"}},
    "preview": {"dir": "goose", "driver": "preview",
                "manifest": {"slug": "goose_preview", "name": "Goose UI Preview", "icon": "GP"}},
    "diag": {"dir": "diag"},    # single file with its own manifest header
}

OPEN, CLOSE = "--[==[badge-app", "]==]"
MAIN_LIMIT = 64 * 1024          # IDE limit for main.lua
APP_QUOTA = 64 * 1024           # per-app storage quota (BADGE_API.md, badge.fs)
SHARE_LIMIT = 48 * 1024         # Share app bundle cap


# --- build ------------------------------------------------------------------

def split_header(src):
    """Return (manifest dict, code) for a single-file app with a header."""
    lines = src.splitlines(keepends=True)
    if not lines or lines[0].strip() != OPEN:
        return None, src
    end = next(i for i, l in enumerate(lines) if l.strip() == CLOSE)
    manifest = {}
    for l in lines[1:end]:
        l = l.strip()
        if l and not l.startswith("#"):
            k, v = l.split("=", 1)
            manifest[k.strip()] = v.strip()
    return manifest, "".join(lines[end + 1:]).lstrip("\n")


def manifest_text(m):
    return "".join(f"{k}={v}\n" for k, v in m.items())


def collect(target):
    """Return (manifest, {module name: source}, {bin name: bytes})."""
    t = TARGETS[target]
    src_dir = APP / t["dir"]
    main_src = (src_dir / "main.lua").read_text()
    header, main_code = split_header(main_src)

    if "driver" not in t:       # plain single-file app
        return header, {"main": main_code}, {}

    modules = {"main": main_src}
    for f in sorted(src_dir.glob("*.lua")):
        name = f.stem
        if name == "main" or (name in DRIVERS and name != t["driver"]):
            continue
        modules[name] = f.read_text()
    modules["driver"] = f'return require("{t["driver"]}")\n'

    images = {}
    for png in sorted((src_dir / "img").glob("*.png")):
        images[png.stem + ".bin"] = png_to_bin(png)
    for b in sorted((src_dir / "img").glob("*.bin")):
        images[b.name] = b.read_bytes()
    return {**t["manifest"], **COMMON}, modules, images


def bundle(manifest, modules):
    """Inline every module into one importable file; returns (text, line map)."""
    out = [OPEN + "\n", manifest_text(manifest), CLOSE + "\n",
           "-- GENERATED by app/tools/badge.py from app/ sources. Do not edit.\n"]
    if len(modules) > 1:
        out.append(
            "local __mods, __cache = {}, {}\n"
            "local function require(name)\n"
            "  local v = __cache[name]\n"
            "  if v ~= nil then return v end\n"
            "  local f = __mods[name]\n"
            "  if not f then error(\"module not found: \" .. name, 2) end\n"
            "  v = f()\n"
            "  if v == nil then v = true end\n"
            "  __cache[name] = v\n"
            "  return v\n"
            "end\n")
    line_map = []
    for name, src in modules.items():
        if name == "main":
            continue
        out.append(f"__mods[{name!r}] = function()  -- ==== {name}.lua ====\n")
        line_map.append((sum(s.count("\n") for s in out) + 1, name))
        out.append(src if src.endswith("\n") else src + "\n")
        out.append("end\n")
    main_code = split_header(modules["main"])[1]
    out.append("-- ==== main.lua ====\n")
    line_map.append((sum(s.count("\n") for s in out) + 1, "main"))
    out.append(main_code)
    return "".join(out), line_map


def build(target):
    manifest, modules, images = collect(target)
    slug = manifest["slug"]
    out_dir = DIST / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    for old in out_dir.iterdir():
        old.unlink()

    files = {"manifest.cfg": manifest_text(manifest).encode()}
    for name, src in modules.items():
        code = split_header(src)[1] if name == "main" else src
        files[f"{name}.lua"] = code.encode()
    files.update(images)
    for name, data in files.items():
        (out_dir / name).write_bytes(data)

    single, line_map = bundle(manifest, modules)
    single_path = DIST / f"{slug}.lua"
    single_path.write_text(single)

    total = sum(len(d) for d in files.values())
    print(f"built {slug}: {len(files)} files, {total} B -> {out_dir.relative_to(APP.parent)}/")
    print(f"  single file for Import app: {single_path.relative_to(APP.parent)} "
          f"({len(single.encode())} B)")
    print("  error line numbers in the single file:",
          ", ".join(f"{n}.lua from line {l}" for l, n in line_map))
    if images:
        print(f"  note: {len(images)} image(s) are only uploaded by `push`, not by Import app")
    if len(single.encode()) > MAIN_LIMIT:
        print(f"  WARNING: single file is over the IDE's {MAIN_LIMIT} B main.lua limit")
    if total > APP_QUOTA:
        print(f"  WARNING: {total} B is over the {APP_QUOTA} B per-app storage quota")
    elif total > SHARE_LIMIT:
        print(f"  note: over {SHARE_LIMIT} B, so the Share app can't send it to other badges")
    return slug, files


# --- images -----------------------------------------------------------------

def png_to_bin(path, size=None):
    """PNG -> LVGL v9 RGB565A8 .bin, same format as the IDE's icon.bin."""
    from PIL import Image
    im = Image.open(path).convert("RGBA")
    if size:
        im = im.resize(size, Image.LANCZOS)
    w, h = im.size
    px = im.tobytes()
    out = bytearray(12 + w * h * 3)
    out[0:4] = bytes([0x19, 0x14, 0, 0])           # magic, RGB565A8, flags
    out[4:12] = (w.to_bytes(2, "little") + h.to_bytes(2, "little")
                 + (w * 2).to_bytes(2, "little") + b"\0\0")
    alpha = 12 + w * h * 2
    for i in range(w * h):
        r, g, b, a = px[i * 4:i * 4 + 4]
        c = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        out[12 + i * 2] = c & 0xFF
        out[13 + i * 2] = c >> 8
        out[alpha + i] = a
    return bytes(out)


# --- push -------------------------------------------------------------------

CHUNK, PAUSE = 128, 0.02     # badge RX ring is 256 B: pace writes like the IDE


def find_port():
    ports = sorted(glob.glob("/dev/cu.usbmodem*") + glob.glob("/dev/ttyACM*"))
    if not ports:
        sys.exit("No badge found. Plug it in (badge off, plug USB, badge on, "
                 "don't hold Start) and close the IDE tab, which holds the port.")
    return ports[0]


def open_port(port):
    """Open the serial port, or exit with a friendly message if it's busy."""
    import serial
    s = serial.Serial()
    s.port, s.baudrate, s.timeout = port, 115200, 0.05
    # pyserial asserts DTR/RTS on open by default; on the ESP32-C3's USB serial
    # that pulses the chip's reset, rebooting the badge and killing the running
    # app. Keep both released, like the web IDE does.
    s.dtr = False
    s.rts = False
    try:
        s.open()
        return s
    except serial.SerialException as e:
        if "busy" in str(e).lower():
            sys.exit(f"{port} is busy: close the badge IDE tab (it holds the port, even "
                     "when disconnected) or any serial monitor, then try again.")
        raise


class Console:
    def __init__(self, port):
        self.s = open_port(port)
        self.buf = ""

    def line(self, text):
        self.s.write((text + "\r").encode())

    def raw(self, data):
        for i in range(0, len(data), CHUNK):
            self.s.write(data[i:i + CHUNK])
            time.sleep(PAUSE)

    def wait(self, pattern, timeout=5.0):
        end = time.time() + timeout
        while time.time() < end:
            self.buf += self.s.read(512).decode(errors="replace")
            i = self.buf.find(pattern)
            if i >= 0:
                got, self.buf = self.buf[:i + len(pattern)], self.buf[i + len(pattern):]
                return got
        raise TimeoutError(f'no "{pattern}" from the badge after {timeout:.0f} s '
                           f"(last output: {self.buf[-200:]!r})")


# --- Session: a higher-level console for scripted play -----------------------
#
# `press` (see BUTTONS below) taps: PRESSED immediately followed by RELEASED.
# Verified 2026-09-19 with `goose_diag` (app/diag/main.lua), which logs every
# transition: `press Left` from the console produced one `down LEFT t=...`
# line immediately followed by one `up LEFT t=... held=<1 ms>` line, held
# always rounds to 0-1 ms. `help press` / `help -v 1` document only
# `press <name>`, no extra arguments (an extra token like `press Left 500` is
# just ignored/not a documented form) -- there is no console way to hold a
# button down. This means the badge console alone cannot exercise game.lua's
# REQUIRE_SEATED (LEFT must be *held*) or SEAT_SETTLE_MS (a seat must stay in
# one state for 150 ms) the way a real seated organ would; see the `t_seated`
# / `t_settle_ms` playtest knobs in game.lua.

BUTTONS = ("A", "B", "Home", "Down", "Left", "Right", "Up", "Aux1", "Start")


_NODE_RE = re.compile(r'^(?:\[\d+\]\s*)?(\S+)\s+(-?\d+),(-?\d+)\s+(\d+)x(\d+)(.*)$')
_TEXT_RE = re.compile(r'text="((?:[^"\\]|\\.)*)"')


class Node:
    """One line of `uitree` output."""
    __slots__ = ("type", "x", "y", "w", "h", "text", "hidden")

    def __init__(self, type_, x, y, w, h, text, hidden):
        self.type, self.x, self.y, self.w, self.h = type_, x, y, w, h
        self.text, self.hidden = text, hidden

    def __iter__(self):   # so callers can do `for kind, x, y, w, h, text in ...`
        return iter((self.type, self.x, self.y, self.w, self.h, self.text))

    def __repr__(self):
        return (f"Node({self.type!r}, {self.x}, {self.y}, {self.w}, {self.h}, "
                f"{self.text!r}, hidden={self.hidden})")


def _decode_stripe(data, count):
    """RLE1: see `shot` in app/CLAUDE.md's playtest section for the format."""
    out = bytearray()
    i, n = 0, 0
    while n < count:
        b = data[i]
        i += 1
        if b & 0x80:
            run = (b & 0x7F) + 2
            px = data[i:i + 2]
            i += 2
            out += px * run
            n += run
        else:
            lit = b + 1
            chunk = data[i:i + 2 * lit]
            i += 2 * lit
            out += chunk
            n += lit
    return bytes(out)


class Session(Console):
    """Console plus the playtest conveniences: cmd/press/uitree/shot/open_app.

    Collects every line the badge prints (command output and unsolicited
    `badge.sys.log` / `I (...)` lines alike) into `self.logs`, so a test can
    grep for a line it expects (e.g. "touch wall 1") no matter which `cmd()`
    call it arrived during.
    """

    def __init__(self, port):
        super().__init__(port)
        self.logs = []
        self.last_cmd = "(handshake)"
        # A freshly-opened port may still have a boot banner (or nothing)
        # queued ahead of a prompt (same trick as push()'s initial `c.line("")`).
        self.buf = ""
        self.line("")
        self.wait("badge> ", 5)

    def cmd(self, text, timeout=5.0):
        """Send one command, return its output text (without the echo or the
        next prompt). Every non-blank line seen is appended to self.logs."""
        self.last_cmd = text   # so a caller can report it if wait() times out
        self.buf = ""
        self.line(text)
        raw = self.wait("badge> ", timeout)
        body = raw[:-len("badge> ")].replace("\r\n", "\n").replace("\r", "\n")
        lines = body.split("\n")
        out_lines, echoed = [], False
        for l in lines:
            if not echoed and l.strip() == text.strip():
                echoed = True   # the console echoing our own command back
                continue
            out_lines.append(l)
        while out_lines and out_lines[-1] == "":
            out_lines.pop()
        for l in out_lines:
            if l.strip():
                self.logs.append(l.strip())
        return "\n".join(out_lines)

    def press(self, name, timeout=5.0):
        """Tap one button (see BUTTONS). PRESSED then RELEASED -- see the
        module docstring above; there is no way to hold from the console."""
        if name not in BUTTONS:
            raise ValueError(f"unknown button {name!r}, expected one of {BUTTONS}")
        return self.cmd(f"press {name}", timeout)

    def uitree(self, timeout=5.0):
        """Return the widget tree as a flat list of Node. `hidden` is true if
        the widget itself is hidden OR any ancestor is (LVGL only marks the
        widget that `hidden(true)` was called on -- e.g. `ui.lua` hides a
        whole screen's box, not each of its labels -- so this walks the
        indentation to work out real, on-screen visibility)."""
        out = self.cmd("uitree", timeout)
        if "UITREE" not in out or "END " not in out:
            raise RuntimeError(f"unexpected uitree output: {out[:300]!r}")
        nodes = []
        stack = []   # (indent, hidden) of open ancestors
        for line in out.splitlines():
            s = line.strip()
            if not s or s in ("top", "(empty)") or s.startswith(("UITREE", "screen ", "END ")):
                continue
            m = _NODE_RE.match(s)
            if not m:
                continue
            indent = len(line) - len(line.lstrip(" "))
            while stack and stack[-1][0] >= indent:
                stack.pop()
            parent_hidden = stack[-1][1] if stack else False
            kind, x, y, w, h, rest = m.groups()
            tm = _TEXT_RE.search(rest)
            hidden = parent_hidden or "hidden" in rest.split()
            stack.append((indent, hidden))
            nodes.append(Node(kind, int(x), int(y), int(w), int(h),
                               tm.group(1) if tm else "", hidden))
        return nodes

    def texts(self, timeout=5.0):
        """Visible label texts, in tree order -- what a test asserts on."""
        return [n.text for n in self.uitree(timeout) if n.text and not n.hidden]

    def shot(self, timeout=10.0, retries=2):
        """Screenshot as a PIL Image. Verifies the crc32 the badge reports."""
        from PIL import Image
        import base64
        import zlib
        last_err = None
        for attempt in range(retries + 1):
            out = self.cmd("shot", timeout)
            try:
                m = re.search(r"SHOT (\d+) (\d+) rgb565le rle1", out)
                if not m:
                    raise RuntimeError(f"no SHOT header: {out[:200]!r}")
                w, h = int(m.group(1)), int(m.group(2))
                buf = bytearray(w * h * 2)
                raw_concat = bytearray()
                lines = out.splitlines()
                i = 0
                stripe_re = re.compile(r"^S (\d+) (\d+) (\d+) (\d+)$")
                while i < len(lines):
                    sm = stripe_re.match(lines[i].strip())
                    if not sm:
                        i += 1
                        continue
                    x0, y0, x1, y1 = (int(g) for g in sm.groups())
                    i += 1
                    b64_lines = []
                    while i < len(lines) and lines[i].strip() and not lines[i].startswith(("S ", "END")):
                        b64_lines.append(lines[i].strip())
                        i += 1
                    data = base64.b64decode("".join(b64_lines))
                    sw, sh = x1 - x0 + 1, y1 - y0 + 1
                    pixels = _decode_stripe(data, sw * sh)
                    raw_concat += pixels
                    for row in range(sh):
                        src = row * sw * 2
                        dst = ((y0 + row) * w + x0) * 2
                        buf[dst:dst + sw * 2] = pixels[src:src + sw * 2]
                endm = re.search(r"END .*crc32=([0-9a-fA-F]+)", out)
                if not endm:
                    raise RuntimeError(f"no END/crc32 in shot output: {out[-200:]!r}")
                want = int(endm.group(1), 16)
                got = zlib.crc32(bytes(raw_concat)) & 0xFFFFFFFF
                if got != want:
                    raise RuntimeError(f"shot crc32 mismatch: got {got:#010x} want {want:#010x}")
                rgb = bytearray(w * h * 3)
                for p in range(w * h):
                    lo, hi = buf[2 * p], buf[2 * p + 1]
                    v = lo | (hi << 8)
                    r5, g6, b5 = (v >> 11) & 0x1F, (v >> 5) & 0x3F, v & 0x1F
                    rgb[3 * p] = r5 * 255 // 31
                    rgb[3 * p + 1] = g6 * 255 // 63
                    rgb[3 * p + 2] = b5 * 255 // 31
                return Image.frombytes("RGB", (w, h), bytes(rgb))
            except TimeoutError:
                # The prompt never came back: don't hammer a possibly-silent
                # console in a retry loop (see app/CLAUDE.md's playtest
                # safety notes) -- surface it immediately.
                raise
            except Exception as e:  # noqa: BLE001 -- decode/crc hiccup: retry, then surface it
                last_err = e
                if attempt == retries:
                    raise
                time.sleep(0.3)
        raise last_err  # pragma: no cover

    def open_app(self, name, max_steps=90, settle=0.15):
        """From wherever the badge is, get to the launcher and open `name`
        (its launcher name, as shown in `apps`' third column).

        The launcher shows the currently-highlighted app's name as a header
        label above the icon grid; that label is the only visible (non
        hidden) `lv_label` outside a tile, so it is found by filtering
        `uitree()`. Navigation order isn't the same as `apps`' listing (icons
        may be reordered by the launcher), so this scans with `press Right`
        rather than assuming a grid position, and stops as soon as the header
        matches. Confirms the open with the `launched <name>` log line.
        """
        self.press("Home")
        time.sleep(settle)
        seen = []
        for _ in range(max_steps):
            header = [n.text for n in self.uitree() if n.text and not n.hidden]
            current = header[0] if header else None
            if current:
                seen.append(current)
            if current == name:
                self.logs.clear()
                self.press("A")
                self.wait_log(f"launched {name}", timeout=3)  # best-effort; doesn't raise
                return
            self.press("Right")
            time.sleep(settle)
        raise RuntimeError(f"never saw {name!r} in the launcher after {max_steps} steps "
                           f"(saw: {seen})")

    def wait_log(self, substr, timeout=3.0):
        """Best-effort: give the badge a moment to print a line containing
        `substr` (e.g. "launched Goose Doctor"), flushing with no-op commands
        so it lands in self.logs. Never raises -- callers should also check
        the screen (uitree/shot), since not every app logs its launch."""
        end = time.time() + timeout
        while time.time() < end and not any(substr in l for l in self.logs):
            try:
                self.cmd("", min(1.0, max(0.05, end - time.time())))
            except TimeoutError:
                break


def push(target, port):
    slug, files = build(target)
    port = port or find_port()
    print(f"pushing to {port} ...")
    c = Console(port)
    try:
        c.line("")
        c.wait("badge> ", 3)
        if any(n.endswith(".bin") for n in files):
            c.buf = ""
            c.line("put --binary")
            if "PUT BINARY OK" not in c.wait("badge> ", 5):
                sys.exit("This badge's firmware can't receive images; update its firmware.")
        remote = f"/littlefs/apps/{slug}"
        c.line(f"mkdir {remote}")
        c.wait("badge> ")
        for name in sorted(files):
            data = files[name]
            print(f"  {name} ({len(data)} B) ...", end=" ", flush=True)
            c.buf = ""
            c.line(f"put {remote}/{name} {len(data)}")
            c.wait("READY")
            c.raw(data)
            c.wait(f"OK {len(data)}", 20)
            print("ok")
        c.buf = ""
        c.line("reload")
        try:
            c.wait("reload:", 8)
            print(f"done: open '{files['manifest.cfg'].decode().split('name=')[1].splitlines()[0]}'"
                  " from the badge launcher")
        except TimeoutError:
            print("uploaded, but reload wasn't confirmed: reboot the badge if the app doesn't appear")
    finally:
        # Close the port: callers (e.g. playtest.py) open their own Session
        # right after push() returns, and the port must be free for that.
        c.s.close()


# --- logs ---------------------------------------------------------------

def emit_line(line, out_f, grep):
    """Timestamp one line, print it (unless filtered by --grep) and append to --out."""
    if grep and grep.lower() not in line.lower():
        return
    stamp = time.strftime("%H:%M:%S") + f".{int(time.time() * 1000) % 1000:03d}"
    stamped = f"{stamp} {line}"
    print(stamped, flush=True)
    if out_f:
        out_f.write(stamped + "\n")
        out_f.flush()


def logs(port, seconds, out, grep):
    """Print the badge's USB serial console (app.log lines, tracebacks, ...)."""
    port = port or find_port()
    s = open_port(port)
    print(f"listening on {port} (Ctrl-C to stop); push can't run while this holds the port",
          file=sys.stderr)
    out_f = open(out, "a") if out else None
    end = time.time() + seconds if seconds is not None else None
    buf = ""
    try:
        while end is None or time.time() < end:
            data = s.read(4096)
            if not data:
                continue
            buf += data.decode(errors="replace").replace("\r\n", "\n").replace("\r", "\n")
            while "\n" in buf:
                line, buf = buf.split("\n", 1)
                emit_line(line, out_f, grep)
    except KeyboardInterrupt:
        pass
    finally:
        if out_f:
            out_f.close()
        s.close()


# --- ui / shot / press / open (thin CLI wrappers around Session) ------------

def cli_ui(port):
    s = Session(port or find_port())
    try:
        for n in s.uitree():
            flag = " hidden" if n.hidden else ""
            text = f' text="{n.text}"' if n.text else ""
            print(f"{n.type} {n.x},{n.y} {n.w}x{n.h}{text}{flag}")
    finally:
        s.s.close()


def cli_shot(port, out):
    s = Session(port or find_port())
    try:
        img = s.shot()
    finally:
        s.s.close()
    out = out or str(DIST / "shots" / f"{time.strftime('%Y%m%d-%H%M%S')}.png")
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(f"wrote {out}")


def cli_press(port, buttons, gap):
    s = Session(port or find_port())
    try:
        for b in buttons:
            s.press(b)
            if gap:
                time.sleep(gap / 1000)
    finally:
        s.s.close()


def cli_open(port, name):
    s = Session(port or find_port())
    try:
        s.open_app(name)
        print(f"opened {name!r}; visible text: {s.texts()}")
    finally:
        s.s.close()


# --- cli --------------------------------------------------------------------

def main():
    p = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = p.add_subparsers(dest="cmd", required=True)
    for cmd in ("build", "push"):
        sp = sub.add_parser(cmd)
        sp.add_argument("target", choices=TARGETS)
        if cmd == "push":
            sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp = sub.add_parser("img")
    sp.add_argument("png")
    sp.add_argument("out")
    sp.add_argument("--size", help="resize to WxH first, e.g. 56x56")
    sub.add_parser("ports")
    sp = sub.add_parser("logs")
    sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp.add_argument("--seconds", type=float,
                     help="stop after N seconds (default: run until Ctrl-C)")
    sp.add_argument("--out", help="also append the timestamped lines to this file")
    sp.add_argument("--grep", help="only show lines containing this text (case-insensitive)")
    sp = sub.add_parser("ui", help="print the uitree: type, position, size, text")
    sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp = sub.add_parser("shot", help="save a screenshot")
    sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp.add_argument("-o", "--out", help="PNG path (default: app/dist/shots/<timestamp>.png)")
    sp = sub.add_parser("press", help="tap one or more buttons")
    sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp.add_argument("buttons", nargs="+", choices=BUTTONS, metavar="BTN")
    sp.add_argument("--gap", type=float, default=0, help="ms to wait between presses")
    sp = sub.add_parser("open", help="navigate the launcher and open an app by name")
    sp.add_argument("--port", help="serial port (default: first /dev/cu.usbmodem*)")
    sp.add_argument("name", help='launcher name, e.g. "Goose Doctor"')
    a = p.parse_args()

    if a.cmd == "build":
        build(a.target)
    elif a.cmd == "push":
        push(a.target, a.port)
    elif a.cmd == "img":
        size = tuple(int(n) for n in re.split("[x×]", a.size)) if a.size else None
        data = png_to_bin(a.png, size)
        Path(a.out).write_bytes(data)
        print(f"wrote {a.out}: {len(data)} B")
    elif a.cmd == "ports":
        print("\n".join(glob.glob("/dev/cu.usbmodem*") + glob.glob("/dev/ttyACM*")) or "none")
    elif a.cmd == "logs":
        logs(a.port, a.seconds, a.out, a.grep)
    elif a.cmd == "ui":
        cli_ui(a.port)
    elif a.cmd == "shot":
        cli_shot(a.port, a.out)
    elif a.cmd == "press":
        cli_press(a.port, a.buttons, a.gap)
    elif a.cmd == "open":
        cli_open(a.port, a.name)


if __name__ == "__main__":
    main()
